#!/bin/bash

session=${1:-awesome}

if [ "$session" != 'awesome' ]; then
    notifier_cmd="notify-send -t 18000 -u critical 'Lock' 'Locking screen in 20 seconds.'"
else
    notifier_cmd="awesome-client \"n=require('naughty');n.notify{title='Lock',text='Locking screen in 20 seconds.',timeout=18,preset=n.config.presets.critical}\""
fi

exec xautolock \
    -detectsleep \
    -time 3 \
    -locker "$HOME/.bin/lock" \
    -notify 20 \
    -notifier "$notifier_cmd"
