#!/bin/bash

# Mounts a luks encrypted device and copies a directory to it.
#
# Example usage: path/to/script /dev/sdc ~/.private
# This would mount device /dev/sdc and copies the directory ~/.private to it.

function gpg_export() {
    gpg --export 0xCD42F58EA2B7D49A > public-keys.gpg
    gpg --export-secret-keys 0xCD42F58EA2B7D49A > secret-keys.gpg
    gpg --export-secret-subkeys 0x921A90CDE0604FAC > secret-subkey-sign.gpg
    gpg --export-secret-subkeys 0x9E38C72EEA5C848F > secret-subkey-encrypt.gpg
    gpg --export-secret-subkeys 0x8FD7960DD1FE623E > secret-subkey-auth.gpg
}

mapname="crypt-${1//\//-}"

cryptsetup luksOpen $1 $mapname
mkdir -p /media/$mapname
mount /dev/mapper/$mapname /media/$mapname

cp -Rf $2 /media/$mapname/
ls -lahR /media/$mapname

umount /media/$mapname
cryptsetup luksClose $mapname

printf "Backup finished. Please remove the storage device.\n"
