#!/bin/bash

# Mounts a luks encrypted device and copies a directory to it.
#
# Example usage: path/to/script /dev/sdc ~/.private
# This would mount device /dev/sdc and copies the directory ~/.private to it.

mapname="crypt-${1//\//-}"

cryptsetup luksOpen $1 $mapname
mkdir -p /media/$mapname
mount /dev/mapper/$mapname /media/$mapname

cp -Rf $2 /media/$mapname/
ls -lahR /media/$mapname

umount /media/$mapname
cryptsetup luksClose $mapname

printf "Backup finished. Please remove the storage device.\n"
