#!/usr/bin/env bash

[[ -z "$DISPLAY" ]] && exit 1

_exists() {
    command -v "$1" &> /dev/null && return 0 || return 1
}

names=()
cmds=()

if _exists qutebrowser && _exists qutebrowser-work; then
    names+=("Qutebrowser (personal)" "Qutebrowser (work)")
    cmds+=("qutebrowser.desktop" "qutebrowser-work.desktop")
elif _exists qutebrowser; then
    names+=("Qutebrowser")
    cmds+=("qutebrowser.desktop")
fi

if _exists firefox; then
    names+=("Firefox")
    cmds+=("firefox.desktop")
fi

if _exists chromium; then
    names+=("Chromium")
    cmds+=("chromium.desktop")
fi

options=()
for i in "${!names[@]}"; do
    options+=("$((i+1)): ${names[$i]}")
done

choice=$(printf '%s\n' "${options[@]}" \
    | rofi -i -lines "${#options[@]}" -width 12 -dmenu -p 'web browser' \
    | cut -d ':' -f 1)

[[ -z "$choice" ]] && exit 0

file="${cmds[$((choice-1))]}"

[[ -n "$file" ]] && gtk-launch "$file" "$@" &> /dev/null
