#!/usr/bin/env bash

# Ask with rofi for a desktop name, create one and move the current node there.
# Commas, colons and spaces get removed from the desktop name.

name=$(rofi -dmenu -i -lines 0 -p "desktop name" -width 20)

[ -z "$name" ] && exit 1

name="${name//[,: ]/$''}"
bspc monitor --add-desktops "$name"

# TODO find a better ways to determine the id of the added desktop
#      right now I simply get the last one in list
id=$(bspc query --desktops --monitor | tail -n1)
bspc node --to-desktop "$id"
