#!/usr/bin/env bash

# Ask with rofi for a new name for the current desktop.
# Commas, colons and spaces get removed.

name=$(rofi -dmenu -i -lines 0 -p "rename desktop" -width 20)

[ -z "$name" ] && exit 1

name="${name//[,: ]/$''}"
bspc desktop --rename "$name"
