#!/usr/bin/env bash
#
# Control monitor brightness.
#
# This script is part of my custom desktop environment. It may not work outside
# of this context.
#
# This script requires `ddcutil`.
# If you need root permissions to run `ddcutil`, run this script with `sudo`.

usage() {
    local prog="${0##*/}"
    cat <<-EOF
	Usage: $prog [<inc|dec|set|get|i|d|s|g>] [<args>]

	Commands:
	  [inc|i] [<value>]
	  [dec|d] [<value>]
	  [set|s] <value>
	  [get|g]
      
	Examples:
	  $prog i 10    # increase by 10%
	  $prog d 10    # decrease by 10%
	  $prog s 50    # set to 50%
	  $prog g       # get in percent
	  $prog         # get in percent
	EOF
}

_ddcutil_default_args() {
    ddcutil --help | grep -q -- '--sleep-less' \
        && echo '--sleep-less --sleep-multiplier .1' \
        || echo '--sleep-multiplier .1'
}

change_brightness() {
    local value="$1"
    local prefix="$2"
    # shellcheck disable=SC2086
    ddcutil $(_ddcutil_default_args) --noverify setvcp 10 $prefix $value
}

get_brightness() {
    ddcutil $(_ddcutil_default_args) --terse getvcp 10 | cut -d" " -f4
}

case "$1" in
    inc|dec|i|d)
        step="${2:-10}"
        case "$1" in
            inc|i)
                change_brightness "$step" +
                ;;
            dec|d)
                change_brightness "$step" -
                ;;
        esac
        ;;
    set|s)
        value="$2"
        [ -z "$value" ] && _usage
        change_brightness "$value"
        ;;
    get|g|'')
        get_brightness
        exit
        ;;
    update)
        ;;
    help)
        usage
        exit
        ;;
    *)
        usage >&2
        exit 1
        ;;
esac

brightness="$(get_brightness)"
[ -n "$brightness" ] && de-panel-send "Cbacklight $brightness%"
