#!/usr/bin/env bash
#
# Get desktop environment configuration.
#
# This script is part of my custom desktop environment. It may not work outside
# of this context.
#
# This script requires `toml` and `jq`.
# It requires $DE_CONFIG to contain the path of a toml file.

if [ ! -r "$DE_CONFIG" ]; then
    printf "%s\n" "Configuration not found: $$DE_CONFIG is not a readable file." >&2
    exit 1
fi

usage() {
    local prog="${0##*/}"
    cat <<-EOF
	Usage: $prog get <args>

	Examples:
	  $prog get pulseaudio.source
	  $prog get pulseaudio '.sink | to_entries[] | .value.name'
	EOF
}

case "$1" in 
    get)
        config="$(toml get "$DE_CONFIG" "$2")"
        [[ "$config" == "null" ]] && exit 1
        if [ -n "$3" ]; then
            jq -r "$3" <<< "$config"
            exit $?
        else
            printf "%s\n" "$config"
        fi
        ;;
    help)
        usage
        ;;
    *) 
        usage >&2
        exit 1
        ;;
esac
