#!/usr/bin/env bash

target_monitor="$1"

. "$HOME/.panel-colors"

render_blue_block() {
    local res bg fg
    [ -z "$1" ] && exit
    if [ "$2" -eq 1 ]; then
        fg="$COLOR_DESKTOP_LAYOUT_FOCUSED_FG"
        bg="$COLOR_DESKTOP_LAYOUT_FOCUSED_BG"
    else
        fg="$COLOR_DESKTOP_LAYOUT_FG"
        bg="$COLOR_DESKTOP_LAYOUT_BG"
    fi
    res="%{F${fg}}%{B${bg}} $1 %{B-}%{F-}"
    printf "%s\n" "$res"
}

render_desktop() {
    local res
    local name="${1#?}"
    local index="$2"
    case "$1" in
        O*)
            fg="$COLOR_DESKTOP_OCCUPIED_FOCUSED_FG"
            bg="$COLOR_DESKTOP_OCCUPIED_FOCUSED_BG"
            ;;
        o*)
            fg="$COLOR_DESKTOP_OCCUPIED_FG"
            bg="$COLOR_DESKTOP_OCCUPIED_BG"
            ;;
        F*)
            fg="$COLOR_DESKTOP_FREE_FOCUSED_FG"
            bg="$COLOR_DESKTOP_FREE_FOCUSED_BG"
            ;;
        f*)
            fg="$COLOR_DESKTOP_FREE_FG"
            bg="$COLOR_DESKTOP_FREE_BG"
            ;;
        U*)
            fg="$COLOR_DESKTOP_URGENT_FOCUSED_FG"
            bg="$COLOR_DESKTOP_URGENT_FOCUSED_BG"
            ;;
        u*)
            fg="$COLOR_DESKTOP_URGENT_FG"
            bg="$COLOR_DESKTOP_URGENT_BG"
            ;;
    esac
    printf "%s\n" "%{F${fg}}%{B${bg}} ${index} | ${name} %{B-}%{F-}"
}

render_volume() {
    local res="$1 $2"
    [[ "$3" == "yes" ]] && res="$res muted"
    printf "%s\n" "$(render_block "$res")"
}

render_date_block() {
    [ -z "$1" ] && exit
    local fg bg
    fg="$COLOR_DATE_FG"
    bg="$COLOR_DATE_BG"
    res="%{F${fg}}%{B${bg}} ${1} %{B-}%{F-}"
    [ -n "$res" ] && printf " %s\n" "$res"
}

render_disabled() {
    local bg fg
    bg="$COLOR_DISABLED_BG"
    fg="$COLOR_DISABLED_FG"
    [ -n "$1" ] && printf " %s\n" "%{F${fg}}%{B${bg}} $1 %{B-}%{F-}"
}

render_block() {
    [ -z "$1" ] && exit
    local fg bg
    fg="$COLOR_BLOCK_FG"
    bg="$COLOR_BLOCK_BG"
    res="%{F${fg}}%{B${bg}} ${1} %{B-}%{F-}"
    [ -n "$res" ] && printf " %s\n" "$res"
}

this_or_empty() {
    [ "$1" == "$2" ] && printf "%s\n" "$3"
}

declare -A disabled_features

while read -r line ; do
    [[ -z "$line" ]] && continue
    # parse input
    case $line in
        L*)
            load="$(render_block "${line#?}")"
            ;;
        D*)
            date="$(render_date_block "${line#?}")"
            ;;
        M*)
            mem="$(render_block "${line#?}")"
            ;;
        T*)
            temp="$(render_block "${line#?}")"
            ;;
        N*)
            mail="$(render_block "${line#?}")"
            ;;
        V*)
            IFS=$' ' read -r speakers_vol speakers_mute headphones_vol headphones_mute mic_vol mic_mute <<< "${line#?}"
            vspeakers="$(render_volume "speakers" "$speakers_vol" "$speakers_mute")"
            vheadphones="$(render_volume "headphones" "$headphones_vol" "$headphones_mute")"
            vmic="$(render_volume "mic" "$mic_vol" "$mic_mute")"
            ;;
        B*)
            bat="$(render_block "${line#?}")"
            ;;
        A*) 
            disabled_features[notifications]="$(this_or_empty "${line#?}" "true" "notifications")"
            ;;
        W*)
            desktops=()
            IFS=':'
            set -- ${line#?}
            monitor_index=0
            while [ $# -gt 0 ] ; do
                # item=${1#?}
                item="$1"
                name="${item#?}"
                case "$item" in
                    [mM]*)
                        ((monitor_index++))
                        [[ "$monitor_index" -ne "$target_monitor" ]] && shift && continue
                        case "$item" in
                            m*) is_monitor_active=0;;
                            M*) is_monitor_active=1;;
                        esac
                        ;;
                    [oOfFuULTG]*)
                        [[ "$monitor_index" -ne "$target_monitor" ]] && shift && continue
                        case "$item" in
                            [oOfFuU]*) desktops+=("$item");;
                            L*) desktop_layout="$name";;
                            T*) node_state="$name";;
                            G*) node_flags="$name";;
                        esac
                        ;;
                esac
                shift
            done
            dl="$(render_blue_block "$desktop_layout" "$is_monitor_active")"
            nl="$(render_blue_block "$node_state" "$is_monitor_active")"
            nf="$(render_blue_block "$node_flags" "$is_monitor_active")"
            ds=
            index=1
            for desktop in "${desktops[@]}"; do
                ds="${ds} $(render_desktop "${desktop}" "${index}")"
                ((index+=1))
            done
            ;;
    esac

    disabled="$(render_disabled "${disabled_features[notifications]}")"

    printf "%s\n" "%{l}${dl}${nl}${nf} ${ds} %{r}${vspeakers}${vheadphones}${vmic}${mail}${load}${mem}${temp}${bat}${disabled}${date}"
done
