#!/usr/bin/env bash
# 
# Send a update message to all desktop panels.
#
# This script is part of my custom desktop environment. It may not work outside
# of this context.
#
# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
# Date: 2021-01-20
# Licence: MIT

# TODO move this path to a shared file
FIFO_BASE=/tmp/panel-fifo

if [ -n "$1" ]; then
    printf "%s\n" "$1" | tee "${FIFO_BASE}_"* > /dev/null
else
    tee "${FIFO_BASE}_"* <&0 > /dev/null
fi
