#!/bin/sh
#
# Toggle the desktop panel.
#
# This script is part of my custom desktop environment. It may not work outside
# of this context.

# TODO move padding to a shared file

_sv() {
    SVDIR=~/service.x sv "$1" de-panel
}

if [ "$(_sv status | cut -d ':' -f 1)" = "run" ]; then
    echo "is up"
    _sv down
    bspc config top_padding 0
else
    echo "is down"
    _sv up
    bspc config top_padding 20
fi
