#!/bin/sh
#
# Toggle the desktop panel.
#
# This script is part of my custom desktop environment. It may not work outside
# of this context.
#
# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
# Date: 2021-01-20
# Licence: MIT

# TODO move padding to a shared file

pkill -xf "bash $(which de-panel)"
if [ $? -eq 0 ]; then
    bspc config top_padding 0
else
    bspc config top_padding 20
    de-panel > /dev/null &
fi
