#!/usr/bin/env bash

# Print temperatures of configured devices.

config="$(de-config get "temp")"
if [ "$?" -gt 0 ]; then
    printf "%s\n" "Configuration not found"
    exit 1
fi

cfg() {
    jq -r "$1" <<< "$config"
}

# Convert a raw temperature value to degree celcius.
celcius() {
    read -r temp <&0
    printf "%s" "$((temp/1000))°C"
}

case "$1" in
    panel)
        # generate output for my lemonbar panel
        while read -r label; do
            read -r path warn crit <<< "$(cfg ".$label | \"\(.path) \(.warn) \(.crit)\"")"
            temp="$(< "$path")"
            if [ "$crit" != "null" ] && [ "$temp" -ge "$crit" ]; then
                state="crit"
            elif [ "$warn" != "null" ] && [ "$temp" -ge "$warn" ]; then
                state="warn"
            else
                state="norm"
            fi
            printf "%s\n" "$(celcius <<< "$temp") $state" 
        done <<< "$(cfg 'keys_unsorted | to_entries[] | .value')" | tr '\n' $' '
        ;;
    *)
        while read -r label; do
            printf "%s\n" "$label $(celcius < "$(cfg ".${label}.path")")" 
        done <<< "$(cfg 'keys_unsorted | to_entries[] | .value')"
        ;;
esac
