#!/bin/zsh

while getopts "t:T:p:usnlh" option; do
  case "$option" in
    t) target="$OPTARG";;
    T) targets="$OPTARG";;
    p) project="$OPTARG";;
    u) git_unstaged_files=true;;
    s) git_staged_files=true;;
    n) git_new_files=true;;
    l) mode_list=true;;
    h) mode_help=true;;
    \?) echo "Invalid option -$OPTARG" >&2;;
  esac
done

if [ $mode_help ]; then
    cat <<-END
Usage: deploy -t [TARGET] [FILE]...

A simple deploy script.

Examples:
  deploy -t dev src/a       # deploy src/a on dev
  deploy -t dev -sun        # deploy uncommited files on dev

Arguments:
  -t TARGET     target to deploy on
  -T FILE       target defition file to use
                if omitted deploy.targets from the project directory is used
  -p DIR        project directory
                if omitted and in a git repository the repository root is used
                otherwise the current working directory
  -u            deploy unstaged files (git)
  -s            deploy staged files (git)
  -n            deploy new/untracked files (git)
  -l            list available targets
  -h            show this help

Deployment:
  The specified files from the local-dir in the project root are packed into a
  gzipped tarball, scp'd to the remote hosts /tmp directory and unpacked to
  remote-dir.

Targets:
  Targets are configured in a file one target per line.
  Lines starting with # and empty lines are ignored.
  Currently only password based authentification is supported. The password is
  read from pass (https://www.passwordstore.org).

Example targets file:
  # target  host             remote-dir       local-dir  pass-key
  dev       user@host.dev    /var/www/htdocs  src        ssh/project/dev
  stage     user@host.stage  /var/www/htdocs  src        ssh/project/stage
END
exit
fi

# find project directory
if [ ! "$project" ]; then
    project=$(git rev-parse --show-toplevel 2> /dev/null || pwd)
fi

# check for file with target definitions
if [ ! $targets ]; then
    targets="$project/deploy.targets"
fi
if [ ! -r "$targets" ]; then
    echo "ERROR: targets file missing"
    return
fi

# list available targets
if [ $mode_list ]; then
    echo "Project:  $project"
    echo "Targets:"
    for t in $(awk '/^[a-zA-Z0-9_\-\/]+ / {print $1}' $targets); do
        echo "  $t"
    done
    return
fi

# get target configuration
if [ ! "$target" ]; then
    echo "ERROR: no target given"
    return
fi
target_config=($(sed -n -e "/^$target /p" $targets))
if [ ! "$target_config" ]; then
    echo "ERROR: Target $target not found."
    return
fi
host=$target_config[2]
rdir=$target_config[3]
ldir=$target_config[4]
passkey=$target_config[5]

if [ ! -d "$project/$ldir" ]; then
    echo "ERROR: $project/$ldir is not a directory"
    exit
fi

# get explitly specified files
files_arg=(${@:$OPTIND})
for file in $files_arg; do
    _abs=$(realpath "$file")
    if [ -f $_abs ] || [ -d $_abs ]; then
        _files=(${_files[@]} $(realpath --relative-to="$project" $file))
    else
        echo "ERROR: file $file doesn't exist"
    fi
done

# get unstaged files
if [ $git_unstaged_files ]; then
    _files=(${_files[@]} $(git ls-files --full-name --modified))
fi

# get staged files
if [ $git_staged_files ]; then
    _files=(${_files[@]} $(git diff --name-only --cached))
fi

# get untracked _files
if [ $git_new__files ]; then
    _files=(${_files[@]} $(git ls-_files --full-name --others --exclude-standard))
fi

# filter out files outside of the deployable directory
for file in $_files; do
    # c=$(find "$project/$ldir" -name $file | wc -l)
    # if [[ $file_count -gt 0 ]]; then
        files=(${files[@]} $file)
    # fi
done


# print some information about the deployment
echo "Project:  $project"
echo "Target:   $target"
echo "  Host:   $host"
echo "  Dir:    $rdir"

if [ ${#files[@]} -eq 0 ]; then
    echo 'ABORT: no files to deploy'
    exit 0
fi

echo "Files:"
for file in $files; do
    echo "  $file"
done

# get connection password from pass
password=$(pass $passkey 2> /dev/null)
if [ ! $password ]; then
    echo "ERROR: no password"
    exit
fi

# create a tgz with the files for deployment
# exclude=( "src/typo3" "src/typo3_src" "src/index.php" "src/composer.*" "src/vendor" )
# param_exclude=( "${exclude[@]/%/\"}" )
# param_exclude=( "${param_exclude[@]/#/--exclude=\"}" )
param_file="--file=/tmp/deploy.tgz"
param_directory="--directory=$project/$ldir"
for file in $files; do
    param_files=(${param_files[@]} $(realpath --relative-to="$project/$ldir/" "$project/$file"))
done
echo -n "Packing ... "
tar --create --gzip $param_directory --exclude-vcs-ignores $param_file $param_files
echo "packed"

# run a ssh or scp command
run_expect() {
    expect <<- DONE
        log_user 0
        set timeout 5
        spawn $1
        expect {
            "assword:" {
                send "$2\r"
                expect eof exit 0
                exit 1
            }
            timeout exit 2
        }
        exit 1
DONE
    case "$?" in
        1) echo "error"; exit 1;;
        2) echo "timeout"; exit 1;;
    esac
}

# copy tgz to remote system
echo -n "Transfering ... "
run_expect "scp /tmp/deploy.tgz $host:/tmp/deploy.tgz" "$password"
echo "transfered"

# unpack and delete tgz
echo -n "Unpacking ... "
run_expect "ssh $host \"tar --directory=$rdir --extract --gzip --file /tmp/deploy.tgz ; rm /tmp/deploy.tgz\"" "$password"
echo " unpacked"
