#!/bin/sh


_usage() {
    printf "%s\n" "Usage: $(basename "$0") [sink-volume|source-volume|sink-mute|source-mute]"
    exit 1
}

getdefaultsink() {
    pacmd stat | gawk -F": " '/^Default sink name: /{print $2}'
}

getdefaultsource() {
    pacmd stat | gawk -F": " '/^Default source name: /{print $2}'
}

getsinkvolume() {
    pacmd list-sinks |
        gawk -v sink="$1" '
            /^\s+ index: [0-9]+/{target = $2 == sink}
            /^\s+\* index: [0-9]+/{target = $3 == sink}
            /^\s+volume: / && target {print $5; exit}
        ' |
        gawk -F"%" '{print $1}'
}

getsourcevolume() {
    pacmd list-sources |
        gawk -v sink="$1" '
            /^\s+ index: [0-9]+/{target = $2 == sink}
            /^\s+\* index: [0-9]+/{target = $3 == sink}
            /^\s+volume: / && target {print $5; exit}
        ' |
        gawk -F"%" '{print $1}'
}

getsinkmute() {
    pacmd list-sinks |
        gawk -v sink="$1" '
            /^\s+ index: [0-9]+/{target = $2 == sink}
            /^\s+\* index: [0-9]+/{target = $3 == sink}
            /^\s+muted: / && target {print $2; exit}
        ' |
        gawk -F"%" '{print $1}'
}

getsourcemute() {
    pacmd list-sources |
        gawk -v sink="$1" '
            /^\s+ index: [0-9]+/{target = $2 == sink}
            /^\s+\* index: [0-9]+/{target = $3 == sink}
            /^\s+muted: / && target {print $2; exit}
        ' |
        gawk -F"%" '{print $1}'
}

[ "$#" -ne 2 ] && _usage

sink="$2"

case "$1" in
    sink-volume)
        # getsinkvolume "$(getdefaultsink)"
        getsinkvolume "$sink"
        ;;
    source-volume)
        getsourcevolume "$sink"
        ;;
    sink-mute)
        getsinkmute "$sink"
        ;;
    source-mute)
        getsourcemute "$sink"
        ;;
    *)
        _usage
        ;;
esac
