#!/usr/bin/env bash

UPDATE_FIFO="/tmp/panel-fifo-updates"

case "$1" in
    all)
        cmds=("alsa Master" "alsa Mic")
        for cmd in "${cmds[@]}"; do
            eval "$0 $cmd"
        done
        ;;
    alsa)
        data="$(amixer get "$2" | sed -n 's/^.*\[\([0-9]\+%\).*\[\(on\|off\)\]$/\1\ \2/p' | uniq)"
        msg="$2 $data"
        prefix="V"
        ;;
    *)
        printf "%s\n" "Invalid command '$1'"
        exit 1
        ;;
esac

printf "%s%s\n" "$prefix" "$msg" > "$UPDATE_FIFO"
