#!/usr/bin/env bash

if [[ -z "$DISPLAY" ]]; then
    echo "\$DISPLAY must not be empty."
    exit 1
fi

OPTIONS=(
    '1: Hibernate'
    '2: Suspend'
    '3: Suspend hybrid'
    '4: Suspend and reboot'
    '5: Reboot'
    '6: Shutdown'
    '7: Logout'
)
CHOICE=$(printf '%s\n' "${OPTIONS[@]}" \
    | rofi -i -width 10 -lines "${#OPTIONS[@]}" -dmenu -p 'session' \
    | cut -d ':' -f 1)

[[ -z "$CHOICE" ]] && exit 1

case "$CHOICE" in
    1) sudo zzz -Z ;;
    2) sudo zzz ;;
    3) sudo zzz -H ;;
    4) sudo zzz -R ;;
    5) sudo shutdown -r now ;;
    6) sudo shutdown -h now ;;
    7) bspc quit ;;
esac
