#!/usr/bin/env bash

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | \
    column -t -s $'\t' | \
    rofi -dmenu -i -no-show-icons -width -100 -lines 25 -yoffset 40 -p search
