#!/usr/bin/env bash

while getopts "n" option; do
  case "$option" in
    n) notifications=true;; 
    \?) printf "%s\n" "Invalid option -$OPTARG" >&2;;
  esac
  shift
done

(
    if ! flock -n -e 200; then
        if [ $notifications ]; then
            notify-send \
                -t 3000 \
                "Mail already get synced. Abort."
        else
            printf "%s\n" "Mail already get synced. Abort."
        fi
        exit 1
    fi

    if [ $notifications ]; then
        notify-send \
            -t 0 \
            -h string:private-synchronous:syncmail \
            "Fetch mail ..."
    else
        printf "%s\n" "Fetch mail ..."
    fi

    mbsync -a
    notmuch new

    notmuch tag +gmail -- 'folder:/gmail\/.*/'
    notmuch tag +posteo -- 'folder:/posteo\/.*/'

    unread="$(notmuch count tag:unread)"
    new="$(notmuch count tag:new)"

    if [ "$new" -gt 0 ]; then
        text="$new new, $unread unread"
    elif [ "$unread" -gt 0 ]; then
        text="No new mail, but $unread still unread"
    else
        text="No new mail"
    fi

    if [ $notifications ]; then
        notify-send \
            -h string:private-synchronous:syncmail \
            "Mail fetched" "$text"
    else
        printf "%s\n" "Mail fetched: $text"
    fi

    notmuch tag -new -- tag:new
) 200>/tmp/syncmail-"$(whoami)"
