#!/usr/bin/env bash

# Find temperature by label.
# Usage: find_temp <dir> <label>
find_temp() {
    local file
    for file in "$1"temp*_label; do
        if [ "$(<"$file")" == "$2" ]; then
            printf "%s" "$(<"${file//_label/_input}")"
        fi
    done
}

# Find and print temperature.
# Usage: temp <dir> <label> <key>
get_temp() {
    local value
    value="$(find_temp "$1" "$2")"
    if [ -n "$value" ]; then
        printf "%s\n" "$3 $value"
    fi
}

# Print temperatures in the order they were found.
print_temps() {
    for dir in /sys/class/hwmon/hwmon*/; do
        case "$(<"$dir/name")" in
            amdgpu) get_temp "$dir" "edge" "gpu" ;;
            k10temp) get_temp "$dir" "Tdie" "cpu" ;;
            nvme) get_temp "$dir" "Composite" "nvme" ;;
        esac
    done
}

# Convert a raw temperature value to degree celcius.
celcius() {
    local temp="$1"
    printf "%s" "$((temp/1000))°C"
}

case "$1" in
    panel)
        # generate output for my lemonbar panel
        declare -A dev
        IFS=$'\n' read -d "" -ra temps <<< "$(print_temps)"
        for temp in "${temps[@]}"; do
            IFS=$' ' read -r name value <<< "$temp"
            dev["$name"]="$value"
        done
        printf "%s\n" "$(celcius "${dev[cpu]}") / $(celcius "${dev[gpu]}") / $(celcius "${dev[nvme]}")"
        ;;
    *)
        # just print the temperatures
        print_temps
        ;;
esac
