#!/usr/bin/env bash

# Find temperature by label.
# Usage: find_temp <dir> <label>
find_temp() {
    local file
    for file in "$1"temp*_label; do
        if [ "$(<"$file")" == "$2" ]; then
            printf "%s" "$(<"${file//_label/_input}")"
        fi
    done
}

# Find and print temperature.
# Usage: temp <dir> <label>
get_temp() {
    local value
    value="$(find_temp "$1" "$2")"
    if [ -n "$value" ]; then
        printf "%s" "$value"
    fi
}

# Convert a raw temperature value to degree celcius.
celcius() {
    local temp="$1"
    printf "%s" "$((temp/1000))°C"
}

declare -A temps
for dir in /sys/class/hwmon/hwmon*/; do
    case "$(<"$dir/name")" in
        amdgpu) temps[gpu]="$(get_temp "$dir" "edge")" ;;
        k10temp) temps[cpu]="$(get_temp "$dir" "Tdie")" ;;
        nvme) temps[nvme]="$(get_temp "$dir" "Composite")" ;;
    esac
done

case "$1" in
    panel)
        # generate output for my lemonbar panel
        printf "%s\n" "$(celcius "${temps[cpu]}") / $(celcius "${temps[gpu]}") / $(celcius "${temps[nvme]}")"
        ;;
    *)
        printf "%s\n" "cpu ${temps[cpu]}" "gpu ${temps[gpu]}" "nvme ${temps[nvme]}"
        ;;
esac
