#!/usr/bin/env bash

usage() {
    local _usage
    read -rd '' _usage <<'EOF'
Usage:
  timer [arguments...]

Arguments:
  -g            ask with rofi for delay and message
  -m MESSAGE    notification message
  -t DELAY      delay as expected by sleep
  -n ARGS       arguments for notify-send

Examples
  alarm -g -n "-u critical"
  alarm -t "10m" -m "Pizza!" 
EOF
    printf '%s\n' "$_usage"
    exit 1
}

while getopts "gm:t:n:" option; do
  case "$option" in
    g) gui=true;; 
    m) message="$OPTARG";;
    t) time="$OPTARG";;
    n) notify_args="$OPTARG";;
    \?) usage;;
  esac
done

if [[ "$gui" ]] && [[ -z "$DISPLAY" ]]; then
    printf "%s\n" "no display"
    exit 1
fi

if [[ "$gui" ]]; then
    [[ -z "$time" ]] && time="$(rofi -i -lines 0 -width -25 -dmenu -p 'countdown')"
    [[ -z "$message" ]] && message="$(rofi -i -lines 0 -dmenu -p 'message')"
fi

if [[ -z "$time" ]]; then
    printf "%s\n" "no time specified"
    usage
fi

message="${message:-Alarm!}"

notify-send "Timer started" "Alarm in $time"

# ignore missing quoting of $time
# shellcheck disable=SC2086
sleep_out="$(sleep $time 2>&1)"

if [[ "$?" -gt 0 ]]; then
    if [[ $gui ]]; then
        notify-send "Timer failed" "$sleep_out"
    else
        printf "%s\n" "Timer failed" "$sleep_out"
    fi
    exit 1
fi

# ignore missing quoting of $notify_args
# shellcheck disable=SC2086
notify-send $notify_args "$message"
