#!/usr/bin/env bash

# usage:
#    vol Master inc 5
#    vol Master dec 5
#    vol Master toggle

case "$2" in
    inc) action="${3}%+" ;;
    dec) action="${3}%-";;
    toggle) action="toggle";;
    *) printf "%s\n" "Invalid command '$2'" && exit 1;;
esac

amixer sset "$1" "$action"
panel-update alsa "$1"
