#!/bin/bash

wttr() {
    # change Paris to your default location
    local request="wttr.in/berlin?lang=de&mFQ"
    [ "$(tput cols)" -lt 125 ] && request+='n'
    curl -H "Accept-Language: ${LANG%_*}" --compressed "$request"
}

wttr
