add_newline = false

[directory]
truncation_length = 12

[battery]
disabled = true

[command_duration]
min_time = 10

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
