#!/usr/bin/env bash

xsetroot -solid "#282828"
xsetroot -cursor_name left_ptr

# rename monitors
IFS=$'\n' read -d "" -ra monitors <<< "$(bspc query --monitors)"
names=(A B C D E F)
for i in "${!monitors[@]}"; do
    bspc monitor "${monitors[$i]}" --rename "${names[$i]}"
done

# TODO move colors and widths to a another file that is shared with the panel script
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.54
bspc config presel_feedback_color "#504945"

bspc config single_monocle false
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config honor_size_hints true
bspc config ignore_ewmh_focus true

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config pointer_modifier mod4

bspc config left_padding -4
bspc config right_padding -4
bspc config bottom_padding -4
bspc config top_padding 22

bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors false

bspc rule --add nagstamon state=floating sticky=on focus=off private=on
bspc rule --add Zathura state=tiled
