#!/usr/bin/env bash

xsetroot -solid "#282828" &

pkill -x sxhkd; sxhkd &
pkill -f "$(which panel)"; panel &
pkill -f "$(which bspwm-event-listener)"; bspwm-event-listener &
dunst &

# rename monitors
IFS=$'\n' read -d "" -ra monitors <<< "$(bspc query --monitors)"
names=(A B C D E F)
for i in "${!monitors[@]}"; do
    bspc monitor "${monitors[$i]}" --rename "${names[$i]}"
done

# TODO move colors and widths to a another file that is shared with the panel script
bspc config border_width 2
bspc config normal_border_color "#504945"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#d79921"
bspc config window_gap 8

bspc config split_ratio 0.5

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config honor_size_hints true
bspc config ignore_ewmh_focus true

bspc config left_padding -4
bspc config right_padding -4
bspc config bottom_padding -4
bspc config top_padding 22

bspc rule --add nagstamon state=floating sticky=on focus=off private=on
bspc rule --add Zathura state=tiled
