[pulseaudio]
    
    [pulseaudio.sink.primary]
    name = "alsa_output.pci-0000_0d_00.1.hdmi-stereo"
    title = "Speakers"

    [pulseaudio.sink.secondary]
    name = "alsa_output.pci-0000_0d_00.4.analog-stereo"
    title = "Headphones"

    [pulseaudio.source.mic]
    name = "alsa_input.pci-0000_0d_00.4.analog-stereo"
    title = "Mic"

[temp]

    [temp.cpu]
    # k10tmp/tdie
    path = "/sys/class/hwmon/hwmon3/temp1_input"
    warn = 65000
    crit = 80000

    [temp.gpu]
    # amdgpu/edge
    path = "/sys/class/hwmon/hwmon2/temp1_input"
    warn = 50000
    crit = 65000

    [temp.nvme1]
    # nvme/Composite
    path = "/sys/class/hwmon/hwmon1/temp1_input"
    warn = 60000
    crit = 75000

    [temp.nvme2]
    # nvme/Composite
    path = "/sys/class/hwmon/hwmon0/temp1_input"
    warn = 60000
    crit = 75000

[monitors]

     [monitors.left]
     name = "A"
     area = "1024x1440+0+0"

     [monitors.middle]
     name = "B"
     area = "2048x1440+1024+0"

     [monitors.right]
     name = "C"
     area = "2048x1440+3072+0"

[fullscreen]

    [fullscreen.full]
    name = "Fullscreen"
    area = "5120x1440+0+0"
    overlaps = ["A", "B", "C"]

    [fullscreen.lpartial]
    name = "Partial Fullscreen (Left)"
    area = "3072x1440+0+0"
    overlaps = ["A", "B"]

    [fullscreen.rpartial]
    name = "Partial Fullscreen (Right)"
    area = "4096x1440+1024+0"
    overlaps = ["B", "C"]

# TODO implement script to use the following configuration
[display.layouts]

    [display.layouts.122]
    name = "3 Virtual Monitors (1024:2048:2048)"

        [display.layouts.122.monitors]
        left   = { name = "A", area = "1024x1440+0+0" }
        middle = { name = "B", area = "2048x1440+1024+0" }
        right  = { name = "C", area = "2048x1440+3072+0" }

        [display.layouts.122.fullscreen]
        full     = { name = "Full",            area= "5120x1440+0+0",    overlaps = ["A", "B", "C"] }
        lpartial = { name = "Partial (left)",  area= "3072x1440+0+0",    overlaps = ["A", "B"] }
        rpartial = { name = "Partial (right)", area= "4096x1440+1024+0", overlaps = ["B", "C"] }

    [display.layouts.11]
    name = "2 Virtual Monitors (2560:2560)"
    
        [display.layouts.11.monitors]
        left  = { name = "A", area = "2560x1440+0+0" }
        right = { name = "B", area = "2560x1440+2560+0" }

        [display.layouts.11.fullscreen]
        full = { name = "Full", area= "5120x1440+0+0", overlaps = ["A", "B"] }


[panel]

    [panel.monitors]
    A = "minimal"
    B = "minimal"
    C = "full"
